import {useMemo,useState} from 'react'
import {addDaysISO} from './lib/dateUtils'
import {ACTIVITY_TYPES,activityLabel,daysSince,lastEngagement} from './organisingData'

const today=new Date().toISOString().slice(0,10)
const makeId=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`

export function ActivityPanel({person,activities,campaigns,followups,onAddActivity,onAddFollowup}){
  const records=activities.filter(a=>a.personId===person.id).sort((a,b)=>b.date.localeCompare(a.date)),last=lastEngagement(person.id,activities),open=followups.filter(f=>f.personId===person.id&&f.status==='open').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),campaignIds=[...new Set(records.flatMap(a=>a.campaignIds))]
  return <section className="activity-panel"><header><div><b>Organising activity</b><span>{last?`Last meaningful engagement ${daysSince(last.date)} days ago`:'No meaningful engagement recorded'}</span></div><button type="button" onClick={onAddActivity}>+ Record activity</button></header>
    <div className="person-signals"><span><b>{records.length}</b> records</span><span><b>{campaignIds.length}</b> campaigns</span><span className={open.some(f=>f.dueDate<today)?'overdue':''}><b>{open.length}</b> follow-ups</span></div>
    {campaignIds.length>0&&<div className="campaign-tags">{campaignIds.map(id=><span key={id}>{campaigns.find(c=>c.id===id)?.name}</span>)}</div>}
    {open.length>0&&<div className="person-followups"><b>Next follow-up</b><span>{open[0].dueDate} · {open[0].purpose} · {open[0].assignedTo}</span></div>}
    <div className="timeline">{records.slice(0,8).map(a=><article key={a.id}><i/><time>{new Date(`${a.date}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</time><div><b>{activityLabel(a.type)}</b><span>{a.campaignIds.map(id=>campaigns.find(c=>c.id===id)?.name).filter(Boolean).join(' · ')}</span>{a.notes&&<p>{a.notes}</p>}</div></article>)}{!records.length&&<p className="empty-copy">No activity recorded yet. This means our picture is incomplete, not that this person is inactive.</p>}</div>
    <button className="followup-link" type="button" onClick={onAddFollowup}>+ Set a follow-up</button>
  </section>
}

export function ActivityModal({person,people,campaigns,onClose,onSave}){
  const [draft,setDraft]=useState({personId:person?.id||people[0]?.id,date:today,type:'meeting',campaignIds:[],structure:'Branch',role:'participant',notes:'',recordedBy:'',followUp:false,followUpDate:'',followUpPurpose:'Check in after activity',assignedTo:''})
  const set=(k,v)=>setDraft(d=>({...d,[k]:v}));return <div className="shade"><section className="activity-modal"><header><div><small>RECORD WHAT HAPPENED</small><h2>Add organising activity</h2></div><button className="icon" onClick={onClose}>×</button></header><div className="activity-form"><label>Person<select value={draft.personId} onChange={e=>set('personId',e.target.value)}>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="pair"><label>Activity<select value={draft.type} onChange={e=>set('type',e.target.value)}>{['Contact','Participation','Contribution','Non-participation'].map(group=><optgroup label={group} key={group}>{ACTIVITY_TYPES.filter(t=>t.group===group).map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</optgroup>)}</select></label><label>Date<input type="date" value={draft.date} onChange={e=>set('date',e.target.value)}/></label></div><label>Campaign<select value={draft.campaignIds[0]||''} onChange={e=>set('campaignIds',e.target.value?[e.target.value]:[])}><option value="">No specific campaign</option>{campaigns.filter(c=>c.status==='active').map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="pair"><label>Structure<input value={draft.structure} onChange={e=>set('structure',e.target.value)} placeholder="Branch, committee, building…"/></label><label>Role<select value={draft.role} onChange={e=>set('role',e.target.value)}><option value="participant">Participant</option><option value="helper">Helped</option><option value="lead">Led or facilitated</option></select></label></div><label>Notes<textarea rows="3" value={draft.notes} onChange={e=>set('notes',e.target.value)} placeholder="What happened? What did they take responsibility for?"/></label><label className="check-row"><input type="checkbox" checked={draft.followUp} onChange={e=>set('followUp',e.target.checked)}/> Create a follow-up from this activity</label>{draft.followUp&&<div className="followup-fields"><div className="pair"><label>Due date<input type="date" value={draft.followUpDate} onChange={e=>set('followUpDate',e.target.value)}/></label><label>Assigned to<input value={draft.assignedTo} onChange={e=>set('assignedTo',e.target.value)}/></label></div><label>Purpose<input value={draft.followUpPurpose} onChange={e=>set('followUpPurpose',e.target.value)}/></label></div>}</div><footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!draft.personId||!draft.date} onClick={()=>onSave({...draft,id:makeId('a')})}>Save activity</button></footer></section></div>
}

export function FollowupModal({person,people,campaigns,onClose,onSave}){const[d,setD]=useState({personId:person?.id||people[0]?.id,campaignId:'',assignedTo:person?.organiser||'',dueDate:'',purpose:'Campaign conversation',notes:'',status:'open'}),set=(k,v)=>setD(x=>({...x,[k]:v}));return <div className="shade"><section className="activity-modal small"><header><div><small>PLAN THE NEXT STEP</small><h2>Set a follow-up</h2></div><button className="icon" onClick={onClose}>×</button></header><div className="activity-form"><label>Person<select value={d.personId} onChange={e=>set('personId',e.target.value)}>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="pair"><label>Due date<input type="date" value={d.dueDate} onChange={e=>set('dueDate',e.target.value)}/></label><label>Assigned to<input value={d.assignedTo} onChange={e=>set('assignedTo',e.target.value)}/></label></div><label>Purpose<select value={d.purpose} onChange={e=>set('purpose',e.target.value)}>{['Invite to meeting','Ask them to take a task','Campaign conversation','Check in after activity','Leadership development','Introduce to organiser','Try contact again','Follow up an issue'].map(x=><option key={x}>{x}</option>)}</select></label><label>Campaign<select value={d.campaignId} onChange={e=>set('campaignId',e.target.value)}><option value="">No specific campaign</option>{campaigns.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Notes<textarea rows="3" value={d.notes} onChange={e=>set('notes',e.target.value)}/></label></div><footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!d.personId||!d.dueDate||!d.assignedTo} onClick={()=>onSave({...d,id:makeId('f')})}>Set follow-up</button></footer></section></div>}

export function AttendanceModal({people,campaigns,onClose,onSave}){const[meta,setMeta]=useState({date:today,type:'meeting',campaignId:'',title:'Branch meeting'}),[states,setStates]=useState({}),[search,setSearch]=useState(''),set=(id,v)=>setStates(s=>({...s,[id]:v}));return <div className="shade"><section className="attendance-modal"><header><div><small>BULK PARTICIPATION</small><h2>Record attendance</h2></div><button className="icon" onClick={onClose}>×</button></header><div className="attendance-meta"><label>Activity name<input value={meta.title} onChange={e=>setMeta({...meta,title:e.target.value})}/></label><label>Date<input type="date" value={meta.date} onChange={e=>setMeta({...meta,date:e.target.value})}/></label><label>Campaign<select value={meta.campaignId} onChange={e=>setMeta({...meta,campaignId:e.target.value})}><option value="">No campaign</option>{campaigns.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><label className="attendance-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people…"/></label><div className="attendance-list">{people.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><div key={p.id}><b>{p.name}</b><span>{p.area}</span><div>{[['attended','Attended'],['apology','Couldn’t attend'],['none','Not expected']].map(([v,l])=><button className={states[p.id]===v?'on':''} onClick={()=>set(p.id,v)} key={v}>{l}</button>)}</div></div>)}</div><footer><span>{Object.values(states).filter(x=>x==='attended').length} attending</span><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(Object.entries(states).filter(([,v])=>v!=='none').map(([personId,v],i)=>({id:makeId(`bulk${i}`),personId,date:meta.date,type:v==='attended'?meta.type:'could-not-attend',campaignIds:meta.campaignId?[meta.campaignId]:[],structure:meta.title,role:'participant',notes:'',recordedBy:''})))}>Save attendance</button></footer></section></div>}

export function FollowupsView({people,campaigns,activities,followups,onComplete,onSelect,onAdd}){const[owner,setOwner]=useState('all'),owners=[...new Set(followups.map(f=>f.assignedTo).filter(Boolean))],rows=useMemo(()=>followups.filter(f=>f.status==='open'&&(owner==='all'||f.assignedTo===owner)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),[followups,owner]),weekEnd=addDaysISO(today,7),groups=[['Overdue',f=>f.dueDate<today],['This week',f=>f.dueDate>=today&&f.dueDate<=weekEnd],['Later',f=>f.dueDate>weekEnd]];return <section className="followups-view"><header><div><small>NEXT ORGANISING STEPS</small><h2>Follow-ups</h2><p>Promises made by organisers, and clear next steps for bringing people in.</p></div><div><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">All organisers</option>{owners.map(x=><option key={x}>{x}</option>)}</select><button className="primary" onClick={onAdd}>+ Set follow-up</button></div></header>{groups.map(([name,test])=>{let items=rows.filter(test);return <div className="followup-group" key={name}><h3>{name}<span>{items.length}</span></h3>{items.map(f=>{let p=people.find(x=>x.id===f.personId),last=lastEngagement(f.personId,activities);return <article key={f.id} className={name==='Overdue'?'overdue':''}><button className="person-link" onClick={()=>onSelect(p.id)}><i>{p?.name.split(/\s/).map(x=>x[0]).join('').slice(0,2)}</i><span><b>{p?.name}</b><small>{p?.area} · {last?`${daysSince(last.date)} days since engagement`:'No engagement recorded'}</small></span></button><div className="followup-purpose"><b>{f.purpose}</b><span>{campaigns.find(c=>c.id===f.campaignId)?.name||'General organising'} · assigned to {f.assignedTo}</span>{f.notes&&<p>{f.notes}</p>}</div><time>{new Date(`${f.dueDate}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</time><button className="complete" onClick={()=>onComplete(f)}>Mark done</button></article>})}{!items.length&&<p className="empty-group">Nothing here.</p>}</div>})}</section>}
