import {useState} from 'react'

const makeId=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`
export default function OrganisingDataTransfer({people,campaigns,activities,followups,onClose,onReplace}){
  const [dataset,setDataset]=useState('activities'),[mode,setMode]=useState('export'),[text,setText]=useState(''),[message,setMessage]=useState('')
  const personNames=new Map(people.map(p=>[p.id,p.name])),campaignNames=new Map(campaigns.map(c=>[c.id,c.name])),campaignByName=new Map(campaigns.map(c=>[c.name.toLowerCase(),c.id]))
  const exports={activities:['activity_id\tperson_id\tperson_name\tdate\ttype\tcampaign\tstructure\trole\tnotes',...activities.map(a=>[a.id,a.personId,personNames.get(a.personId)||'',a.date,a.type,a.campaignIds.map(id=>campaignNames.get(id)||id).join('; '),a.structure||'',a.role||'',a.notes||''].join('\t'))].join('\n'),followups:['follow_up_id\tperson_id\tperson_name\tcampaign\tassigned_to\tdue_date\tpurpose\tstatus\tnotes',...followups.map(f=>[f.id,f.personId,personNames.get(f.personId)||'',campaignNames.get(f.campaignId)||'',f.assignedTo,f.dueDate,f.purpose,f.status,f.notes||''].join('\t'))].join('\n'),campaigns:['campaign_id\tname\tstatus\towner\tdescription',...campaigns.map(c=>[c.id,c.name,c.status,c.owner,c.description].join('\t'))].join('\n')}
  const copy=async()=>{await navigator.clipboard.writeText(exports[dataset]);setMessage('Copied for Google Sheets')}
  const importRows=()=>{const rows=text.trim().split(/\r?\n/).slice(1).map(r=>r.split('\t'));if(!rows.length)return setMessage('Paste at least one data row.');if(dataset==='activities')onReplace('activities',rows.map((r,i)=>({id:r[0]||makeId(`a${i}`),personId:r[1],date:r[3],type:r[4],campaignIds:(r[5]||'').split(';').map(x=>campaignByName.get(x.trim().toLowerCase())||x.trim()).filter(Boolean),structure:r[6]||'',role:r[7]||'participant',notes:r[8]||'',recordedBy:''})));if(dataset==='followups')onReplace('followups',rows.map((r,i)=>({id:r[0]||makeId(`f${i}`),personId:r[1],campaignId:campaignByName.get((r[3]||'').toLowerCase())||r[3]||'',assignedTo:r[4],dueDate:r[5],purpose:r[6],status:r[7]||'open',notes:r[8]||''})));setMessage(`Imported ${rows.length} ${dataset}.`)}
  return <div className="shade"><section className="activity-modal data-transfer"><header><div><small>PORTABLE ORGANISING DATA</small><h2>Activity data</h2></div><button className="icon" onClick={onClose}>×</button></header><nav>{['activities','followups','campaigns'].map(x=><button key={x} className={dataset===x?'on':''} onClick={()=>{setDataset(x);setMessage('')}}>{x==='followups'?'Follow-ups':x[0].toUpperCase()+x.slice(1)}</button>)}</nav><div className="data-mode"><button className={mode==='export'?'on':''} onClick={()=>setMode('export')}>Export</button><button className={mode==='import'?'on':''} disabled={dataset==='campaigns'} onClick={()=>setMode('import')}>Import & replace</button></div><div className="activity-form"><p>Stable person IDs keep activity connected to the right people when names change.</p>{mode==='export'?<textarea rows="14" readOnly value={exports[dataset]}/>:<textarea rows="14" value={text} onChange={e=>setText(e.target.value)} placeholder={`Paste ${dataset} rows here, including the header row…`}/>} {message&&<div className="data-message">{message}</div>}</div><footer><button className="secondary" onClick={onClose}>Close</button>{mode==='export'?<button className="primary" onClick={copy}>Copy for Google Sheets</button>:<button className="primary" disabled={!text.trim()} onClick={importRows}>Replace {dataset}</button>}</footer></section></div>
}
